config/routes.rb
Rails.application.routes.draw do

  get 'bookings/new'

  root 'flights#index'

  resources :flights,  only: [:index]
  resources :bookings, only: [:index, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departures, foreign_key: "depart_airport_id", class_name: "Flight"
  has_many :arrivals, foreign_key: "arrive_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :passenger
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :depart_airport, class_name: "Airport"
  belongs_to :arrive_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings
  
  def arrive_time
    depart_time + duration
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find params[:flight_id]
    @bookings = Array.new(params[:passengers].to_i){ @flight.bookings.build }
  end
  
  def create
    flight = Flight.find params[:flight_id]
    booking_params = params.permit(:name => [])
    params[:name].each do |i, name|
      passenger = Passenger.find_or_create_by(name: name, email: params[:email][i])
      unless flight.passengers.find_by(name: name)
        flight.passengers << passenger
        PassengerMailer.thank_you(passenger, passenger.bookings.where(flight: flight).first).deliver_now!
        flight.save
      end
    end
    redirect_to root_url
  end
  
  def show
    @booking = Booking.find params[:id]
  end
  
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |a| [a.code, a.id] }
    @dates = Flight.select(:depart_time).distinct.uniq { |f| f.depart_time.to_date } .map { |f| [format_date(f.depart_time), f.depart_time.to_date] }
    if params[:commit] == "Search"
      @flights = Flight.where("depart_airport_id = ? AND arrive_airport_id = ? AND depart_time BETWEEN ? AND ?",
                               params[:depart_airport_id],
                               params[:arrive_airport_id],
                               params[:date].to_datetime,
                               params[:date].to_datetime + 1 - 1/(24.0 * 60 * 60))
      @passengers = params[:passengers]
    end
  end
  
  private
  
    def format_date date
      date.strftime("%m/%d/%Y")
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def format_duration duration
    duration_hours = duration/3600
    duration_minutes = duration/60 - duration_hours*60
    "#{duration_hours}:#{'%02d' % duration_minutes}"
  end
end

app/views/bookings/new.html.erb
<h1>Flight:</h1>
<%= render @flight %>
<%= form_tag bookings_path do %>
  <ul>
    <% @bookings.each_with_index do |b, i| %>
      <li>
        <%= fields_for b.passenger do |p_form| %>
          <%= label_tag "name[#{i}]", "Passenger #{i+1} Name:" %>
          <%= p_form.text_field "name[#{i}]" %>
          <%= label_tag "email[#{i}]", "Passenger #{i+1} Email:" %>
          <%= p_form.email_field "email[#{i}]" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= hidden_field_tag(:flight_id, @flight.id) %>
  <%= submit_tag("Book This Flight") %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking information for <%= @booking.passenger.name %></h1>
<%= render @booking.flight %>

app/views/flights/_flight.html.erb
<span>
  <h3>Flight from <%= flight.depart_airport.code %> to <%= flight.arrive_airport.code %></h3>
  <div>Date: <%= flight.depart_time.to_date %></div>
  <div>Departure Time: <%= flight.depart_time.strftime('%H:%M') %></div> 
  <div>Arrival Time: <%= flight.arrive_time.strftime('%H:%M') %></div>
  <div>Duration: <%= format_duration(flight.duration) %></div>
</span>

app/views/flights/index.html.erb
<h1>Search for a flight</h1>
<%= form_tag("/flights", method: "get") do %>
  <%= select_tag(:depart_airport_id, options_for_select(@airport_options)) %>
  <%= select_tag(:arrive_airport_id, options_for_select(@airport_options)) %>
  <%= select_tag(:passengers, options_for_select([1,2,3,4])) %>
  <%= select_tag(:date, options_for_select(@dates)) %>
  <%= submit_tag("Search") %>
<% end %>

<% if !@flights.nil? && @flights.any? %>
  <h2>Flights:</h2>
  <%= form_tag("/bookings/new", method: "get") %>
    <% @flights.each do |flight| %>
      <%= radio_button_tag(:flight_id, flight.id) %>
      <%= label_tag("flight-id-#{flight.id}", render(flight) ) %>
    <% end %>
    <%= hidden_field_tag(:passengers, @passengers) %>
    <%= submit_tag("Continue") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>